### ISSUE TITLE
Restart on success

### ISSUE THREAD

**Issue by brianhanifin** [custom-components/config_check#2]
## Is your feature request related to a problem? Please describe.
As discussed in Issue #1 it would be awesome if you could add an optional `restart_service` parameter. 

## Describe the solution you'd like
If the restart_service parameter is set then a second service should spawn. Perhaps called `check_config.check_and_restart`?

## Describe alternatives you've considered
Currently I have two buttons side-by-side: "Check Config" and "Restart Home Assistant". This is much nicer than my previous solution so thank you. However, I still have to open the notifications, to verify the success or failure of the check, then click the restart button.

This feature would give us more time to add features to our Automated Homes! :)

## Additional context
Everyone has a different way to restart Home Assistant. Since I run Home Assistant in Docker on a Linux server, I call a shell command `shell_command.restart_hass`. This command uses HADockermon to restart the Home Assistant Docker via a REST API. In my case the shell command calls `curl http://10.0.0.56:8126/container/homeassistant/restart`.

It would be awesome to allow everyone to specify the way they want to restart Home Assistant, no matter how they have it installed!

**Comment by ludeeus** [comment]
right... I forgot about that...

out of curiosity, have you seen this?
https://github.com/custom-components/switch.hadockermon

**Comment by brianhanifin** [comment]
> right... I forgot about that...
> 
> out of curiosity, have you seen this?
> https://github.com/custom-components/switch.hadockermon

Yes I have. Although I have been using [Portainer](https://www.portainer.io) to manage my docker containers, so I haven't experimented with it yet. Although upon a second look I see that I could monitor the attributes to alert me or even restart a service that exceeds its fair share of the resources. Hmm. I think I will add that to my *to look into list* after all. :)

**Comment by ludeeus** [comment]
the image is not correct anymore, I have started the process of making it HA ready and had to split that out.
Will probably do some work with it in the upcoming weeks

**Comment by brianhanifin** [comment]
I assume you mean `config_check`? Or are you talking about the `switch.hadockermon` image?

**Comment by ludeeus** [comment]
`switch.hadockermon` image

Additions to `config_check` I can probably later today/weekend

**Comment by ludeeus** [comment]
Should be OK now (with version 0.1.0) :)

**Comment by brianhanifin** [comment]
OK, remembering that I am not running HASS.IO, how do I configure it to only restart if the check is ok?

So I have a script that executes config_check.run that looks like this.
```yaml
#script
config_check:
  sequence:
    - service: config_check.run
```

How would I add your JSON config values to my non-bass.io setup? Do I add it under the `check_config:` section of my configuration.yaml file?

```yaml
#configuration.yaml
config_check:
  service: shell_command.restart_hass
```

Do I create another script something like this?
```yaml
#script
config_check_and_restart:
  sequence:
    - service: config_check.run
      data:
        service: shell_command.restart_hass
```

**Comment by ludeeus** [comment]
Home Assistant is the same on all platforms ;)

I believe your script example should work, feel free to add it to the Readme when you get something working 👍

**Comment by brianhanifin** [comment]
I wasn't able to figure out how to implement the restart after config successful with your built in parameter, but I was just able to get it to work with the following script.

```
script:
    config_check_and_restart:
    sequence:
        # Clear any old config check notifications
        - service: persistent_notification.create
        data:
            notification_id: "1337"
            title: "Check is running..."
            message: ""

        # Run the config_check
        - service: config_check.run

        # Wait for the notification to appear
        - wait_template: "{{ states('persistent_notification.1337') is string }}"
        timeout: 00:02:00

        # Restart only if the configuration is OK
        - condition: template
        value_template: "{{ state_attr('persistent_notification.1337','message') == 'Configuration is OK!' }}"

        # Clear any old config check notifications
        - service: persistent_notification.create
        data:
            notification_id: "1337"
            title: "Restarting..."
            message: "Home Assistant is restarting!"
        
        - delay:
            seconds: 5

        - service: script.restart_hass
```

The changing of the persistence message is done because I have added a useful markdown card to display the output. And it gives nice progress messages.

```
              type: custom:useful-markdown-card
              content: >-
                ### [[ persistent_notification.1337.attributes.title ]]

                [[ persistent_notification.1337.attributes.message ]]
```
