### ISSUE TITLE
Config check result incomplete in persistent notification

### ISSUE THREAD

**Issue by pplucky** [custom-components/config_check#4]
## Version of the custom_component
Latest

## Describe the bug
Config check log in persistent notification is incomplete

## Configuration

```yaml

switch:
  - platform: command_line
    switches:
      kodi_sala_autoplay:
        friendly_name: "Kodi Sala Autoplay"
        command_on: "curl -s -X POST -d '{\"jsonrpc\":\"2.0\",\"method\":\"Settings.SetSettingValue\",\"params\":{\"setting\":\"videoplayer.autoplaynextitem\",\"value\":[2,4]},\"id\":1}' -H 'Content-type: application/json' http://172.16.23.48:9991/jsonrpc"
        command_off: "curl -s -X POST -d '{\"jsonrpc\":\"2.0\",\"method\":\"Settings.SetSettingValue\",\"params\":{\"setting\":\"videoplayer.autoplaynextitem\",\"value\":[]},\"id\":1}' -H 'Content-type: application/json' http://172.16.23.48:9991/jsonrpc"
        command_state: "curl -s -X POST -d '{\"jsonrpc\":\"2.0\",\"method\":\"Settings.GetSettingValue\",\"params\":{\"setting\":\"videoplayer.autoplaynextitem\"},\"id\":1}' -H 'Content-type: application/json' http://172.16.23.48:9991/jsonrpc"
        value_template: >-
           {% if value_json %} 
              {{ value_json.result[\"value\"][0] in (0,1,2,3,4) }}
           {% endif %}
```

## Log

Persistent notification generated:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/16407309/97876086-38d50200-1d13-11eb-9485-5ef9c1656a4b.png">

If I run the 'Configuration Check' from the HA option:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/16407309/97876167-56a26700-1d13-11eb-8654-8399d43bd486.png">

```
